-- ============================================================
-- Migration 003 : Seed des 67 services du catalogue
-- ============================================================
-- Tous les prix sont en CENTIMES (integer).
-- buffer_minutes par défaut = 0 (à paramétrer ensuite par l'utilisatrice).
-- ============================================================

INSERT INTO catalogue_services (name, category, duration_minutes, buffer_minutes, base_price_cents) VALUES
  ('Soin Purifiant Dos',              'Soins corps',     45, 0, 4500),
  ('Menton',                          'Épilation',       10, 0,  900),
  ('Sourcils Cire',                   'Épilation',       10, 0, 1200),
  ('3/4 Jambes + Aisselles + MS',     'Forfait',         70, 0, 5200),
  ('Cuisses + Aisselles + MI',        'Forfait',         65, 0, 5700),
  ('Dépose Definitive',               'Onglerie',        30, 0, 1500),
  ('Californien',                     'Soins corps',     60, 0, 6000),
  ('Escapade Complète',               'Soins corps',     75, 0, 7500),
  ('3/4 Jambes',                      'Épilation',       35, 0, 2800),
  ('Cuisses',                         'Épilation',       15, 0, 2400),
  ('Dos Homme',                       'Épilation',       30, 0, 2700),
  ('Frais kilométriques',             'Épilation',        5, 0,  432),
  ('Aisselles + Maillot Intégral',    'Forfait',         50, 0, 3500),
  ('Nail Art Complexe',               'Onglerie',        10, 0,  500),
  ('1/2 Jambes + Aisselles + MI',     'Forfait',         70, 0, 5500),
  ('Aisselles',                       'Épilation',       15, 0, 1400),
  ('Demi Bras',                       'Épilation',       15, 0, 2000),
  ('Jambes Complètes + Aiss + MS',    'Forfait',         65, 0, 5600),
  ('Sourcils à la pince',             'Épilation',       15, 0, 1500),
  ('Sourcils au fil',                 'Épilation',       15, 0, 1400),
  ('Forfait Couleur',                 'Coiffure femme',  80, 0,    0),
  ('Aisselles + Maillot Simple',      'Forfait',         35, 0, 2500),
  ('Maquillage mariée avec essais',   'Maquillage',      45, 0, 5000),
  ('1/2 Jambes + Aisselles + ME',     'Forfait',         60, 0, 5000),
  ('Remplissage',                     'Onglerie',        75, 0, 3500),
  ('Teinture',                        'Maquillage',      15, 0, 1700),
  ('Permanente',                      'Coiffure femme',  75, 0,    0),
  ('Visage',                          'Forfait',         15, 0, 2700),
  ('Bras',                            'Épilation',       35, 0, 2700),
  ('Nail Art Simple',                 'Onglerie',         5, 0,  250),
  ('Modelage Cuir Chevelu',           'Plus beauté',      5, 0,  500),
  ('Cours Maquillage',                'Maquillage',      30, 0, 3000),
  ('Jambes Homme',                    'Épilation',       45, 0, 3700),
  ('Modelage mains',                  'Plus beauté',      5, 0,  500),
  ('Maillot Simple',                  'Épilation',       20, 0, 1700),
  ('Lèvres Fil',                      'Épilation',       10, 0, 1400),
  ('Soin selon type de peau',         'Soins visage',    45, 0, 4800),
  ('Cuisses + Aisselles + MS',        'Forfait',         50, 0, 4700),
  ('Jambes Complètes + Aiss + ME',    'Forfait',         70, 0, 6000),
  ('Torse Homme',                     'Épilation',       30, 0, 2700),
  ('Vernis semi-permanent',           'Onglerie',        60, 0, 3500),
  ('Gommage Corps',                   'Soins corps',     15, 0, 1500),
  ('Rallongement',                    'Onglerie',        75, 0, 4500),
  ('Bras Homme',                      'Épilation',       45, 0, 3000),
  ('Maquillage Soir',                 'Maquillage',      30, 0, 2900),
  ('Remise en Beauté',                'Plus beauté',      5, 0,  300),
  ('Modelage Corps',                  'Soins corps',     30, 0, 3000),
  ('Jambes Complètes',                'Épilation',       30, 0, 3200),
  ('Maquillage Jour',                 'Maquillage',      25, 0, 2700),
  ('Dépose',                          'Onglerie',        20, 0,  500),
  ('Soin Mains / Pieds',              'Onglerie',        30, 0, 3000),
  ('Maillot Intégral',                'Épilation',       35, 0, 2700),
  ('Lèvres Cire',                     'Épilation',       10, 0, 1200),
  ('Recourbement Cils',               'Maquillage',      45, 0, 4200),
  ('Cuisses + Aisselles + ME',        'Forfait',         60, 0, 5200),
  ('Gainage Gel',                     'Onglerie',        60, 0, 4000),
  ('Aisselles Homme',                 'Épilation',       10, 0, 1400),
  ('Modelage',                        'Soins visage',    30, 0, 2500),
  ('Modelage dos',                    'Soins corps',     30, 0, 2000),
  ('Aisselles + Maillot (échancré)',  'Forfait',         40, 0, 3000),
  ('3/4 Jambes + Aisselles + ME',     'Forfait',         75, 0, 5700),
  ('3/4 Jambes + Aisselles + MI',     'Forfait',         75, 0, 6000),
  ('1/2 Jambes',                      'Épilation',       20, 0, 2200),
  ('Jambes Complètes + Aiss + MI',    'Forfait',         80, 0, 6500),
  ('Maillot Échancré',                'Épilation',       25, 0, 2200),
  ('Bande supp',                      'Épilation',       10, 0,  500),
  ('1/2 Jambes + Aisselles + MS',     'Forfait',         55, 0, 4600);
